// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKxJHKI0A76xkiKG84FuH7kb0qYnGYqYs',
    appId: '1:621536276011:web:c01a824dffbeb24394846e',
    messagingSenderId: '621536276011',
    projectId: 'listaestudos-9ed61',
    authDomain: 'listaestudos-9ed61.firebaseapp.com',
    storageBucket: 'listaestudos-9ed61.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuRqcXFFcKDRyQdMqrH1SWnMPMMePQU-M',
    appId: '1:621536276011:android:b11f166b47a31d3494846e',
    messagingSenderId: '621536276011',
    projectId: 'listaestudos-9ed61',
    storageBucket: 'listaestudos-9ed61.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlmZlSeNZZ7_BGgsra3f-vZPrk4y2S6Hc',
    appId: '1:621536276011:ios:c75d66ca7ebd2a6c94846e',
    messagingSenderId: '621536276011',
    projectId: 'listaestudos-9ed61',
    storageBucket: 'listaestudos-9ed61.firebasestorage.app',
    iosBundleId: 'com.example.listaEstudos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlmZlSeNZZ7_BGgsra3f-vZPrk4y2S6Hc',
    appId: '1:621536276011:ios:c75d66ca7ebd2a6c94846e',
    messagingSenderId: '621536276011',
    projectId: 'listaestudos-9ed61',
    storageBucket: 'listaestudos-9ed61.firebasestorage.app',
    iosBundleId: 'com.example.listaEstudos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKxJHKI0A76xkiKG84FuH7kb0qYnGYqYs',
    appId: '1:621536276011:web:14718efdd75bf9ef94846e',
    messagingSenderId: '621536276011',
    projectId: 'listaestudos-9ed61',
    authDomain: 'listaestudos-9ed61.firebaseapp.com',
    storageBucket: 'listaestudos-9ed61.firebasestorage.app',
  );
}
